ALTER TABLE User
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY,
ADD COLUMN username VARCHAR(255),
ADD COLUMN name VARCHAR(255),
ADD COLUMN address VARCHAR(255),
ADD COLUMN phone_number VARCHAR(20),
ADD COLUMN email VARCHAR(255),
ADD COLUMN password VARCHAR(255);
