version: '3.8'

services:
  mariadb:
    image: mariadb:11.4
    container_name: shop_mariadb
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "shop_db"
      MYSQL_USER: "shop_user"
      MYSQL_PASSWORD: "shop_password"
    volumes:
      - ./db/mariadb_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    restart: always
networks:
  default:
    driver: bridge